// Generated by CoffeeScript 1.6.3
var Index, esprima;

(require('source-map-support')).install({
  handleUncaughtExceptions: false
});

esprima = require('esprima');

module.exports = new (Index = (function() {
  function Index() {}

  Index.prototype.type = 'script';

  Index.prototype.name = 'javascript';

  Index.prototype.output = 'js';

  Index.prototype.ext = /\.js$/m;

  Index.prototype.exts = ['.js'];

  Index.prototype.compile = function(filepath, source, debug, error, done) {
    var err;
    try {
      esprima.parse(source);
    } catch (_error) {
      err = _error;
      if (err != null) {
        done('');
        return error(err);
      }
    }
    return done(source);
  };

  return Index;

})());

/*
//@ sourceMappingURL=index.map
*/
